server:
  port: 9527

spring:
  application:
    name: clould-gateway-service
  # 配置gateway
  cloud:
    gateway:
      routes:
      # id 属性的值随便起的,只要保证唯一就可以
      - id: payment_route
        # 只能绑定某一个具体的服务提供者
#        uri: http://localhost:8001
#        predicates:
#          - Path=/payment/*
        # 根据服务名负载均衡调用 动态路由
        uri: lb://CLOULD-PAYMENT-SERVICE
        predicates:
          - Path=/payment/*


# 配置服务注册
eureka:
  client:
    # 表示将自己注册进EurekaServer,默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息,默认为true. 单节点无所谓,集群必须设置为true,才能配置ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
  instance:
    instance-id: gateway9527
    prefer-ip-address: true # 访问路径可以显示IP地址
    # Eureka客户端向服务端发送心跳的时间间隔,单位为秒(默认30秒)
    lease-renewal-interval-in-seconds: 5
    # Eureka服务端收到最后一次心跳后等待时间上限,单位为秒(默认90秒),超时则剔除该服务
    lease-expiration-duration-in-seconds: 10