# 配置端口信息
server:
  port: 8002

spring:
  application:
    name: clould-payment-service
  # 配置数据源信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ms_hoxton_sr1_payment?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root

# 配置服务注册
eureka:
  client:
    # 表示将自己注册进EurekaServer,默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息,默认为true. 单节点无所谓,集群必须设置为true,才能配置ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
  instance:
    instance-id: payment8002
    prefer-ip-address: true # 访问路径可以显示IP地址
    # Eureka客户端向服务端发送心跳的时间间隔,单位为秒(默认30秒)
    lease-renewal-interval-in-seconds: 5
    # Eureka服务端收到最后一次心跳后等待时间上限,单位为秒(默认90秒),超时则剔除该服务
    lease-expiration-duration-in-seconds: 10


# 配置mybatis-plus信息
mybatis-plus:
  configuration:
    # 开启驼峰
    map-underscore-to-camel-case: true
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml
  # 配置类型别名所对应的包名
  type-aliases-package: com.cp.company.pojo
  # 扫描通用枚举类所在的包
  type-enums-package: com.cp.company.enums

# 配置PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
